[package]
name = "evm_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dtvmcore_rust = { path = "../" }
cty = "0.2.2"
hex = "0.4"
sha3 = "0.10"
ethabi = "18.0"
